version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.10
jobs:
  push-app:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - aws-code-deploy/push-bundle:
          application-name: nyan_cat
          bundle-source: .
          bundle-bucket: cw-nyancat-demo-bucket
          bundle-key: nyan_cat
          bundle-type: zip
workflows:
  nyan-deploy:
    jobs:
      - push-app
